"""Environment lock and smoke-test helpers."""

from __future__ import annotations

from dataclasses import dataclass
from importlib import metadata as importlib_metadata
import platform
import shutil
import subprocess
import sys
from typing import Callable

import pandas as pd


@dataclass(frozen=True)
class PackageSpec:
    """Package name and optional import module for smoke checks."""

    package: str
    module: str | None = None


BASE_PACKAGES: tuple[PackageSpec, ...] = (
    PackageSpec("anndata"),
    PackageSpec("h5py"),
    PackageSpec("numpy"),
    PackageSpec("pandas"),
    PackageSpec("PyYAML", "yaml"),
    PackageSpec("scipy"),
    PackageSpec("scikit-learn", "sklearn"),
    PackageSpec("statsmodels"),
    PackageSpec("joblib"),
    PackageSpec("matplotlib"),
    PackageSpec("pytest"),
    PackageSpec("ruff"),
    PackageSpec("xgboost"),
    PackageSpec("lightgbm"),
    PackageSpec("catboost"),
)

LATENT_PACKAGES: tuple[PackageSpec, ...] = (
    PackageSpec("scanpy"),
    PackageSpec("scvi-tools", "scvi"),
    PackageSpec("torch"),
    PackageSpec("dask", "dask"),
    PackageSpec("numba"),
    PackageSpec("pynndescent"),
    PackageSpec("zarr"),
)

R_PACKAGES: tuple[str, ...] = (
    "data.table",
    "edgeR",
    "limma",
    "optparse",
    "Matrix",
    "SingleCellExperiment",
    "miloR",
)


def package_rows(
    specs: tuple[PackageSpec, ...],
    *,
    group: str,
    version_lookup: Callable[[str], str | None] | None = None,
) -> list[dict[str, str]]:
    """Return package/version rows for a group."""

    lookup = version_lookup or installed_version
    rows = []
    for spec in specs:
        version = lookup(spec.package)
        rows.append(
            {
                "group": group,
                "package": spec.package,
                "module": spec.module or spec.package.replace("-", "_"),
                "version": version or "",
                "status": "present" if version else "missing",
            }
        )
    return rows


def installed_version(package: str) -> str | None:
    """Return an installed package version, if available."""

    try:
        return importlib_metadata.version(package)
    except importlib_metadata.PackageNotFoundError:
        return None


def lockfile_text(rows: list[dict[str, str]], *, title: str) -> str:
    """Render package rows as a pip-compatible direct lock file."""

    lines = [
        f"# {title}",
        f"# Python: {platform.python_version()}",
        "# Generated by scripts/build_environment_report.py",
        "",
    ]
    for row in sorted(rows, key=lambda item: item["package"].lower()):
        package = row["package"]
        version = row["version"]
        if version:
            lines.append(f"{package}=={version}")
        else:
            lines.append(f"# MISSING: {package}")
    return "\n".join(lines) + "\n"


def runtime_rows() -> list[dict[str, str]]:
    """Collect local runtime metadata for the environment report."""

    return [
        {"key": "platform", "value": platform.platform()},
        {"key": "machine", "value": platform.machine()},
        {"key": "processor", "value": platform.processor()},
        {"key": "python_version", "value": platform.python_version()},
        {"key": "python_executable", "value": sys.executable},
        {"key": "pip_version", "value": _command_text([sys.executable, "-m", "pip", "--version"])},
        {"key": "rscript_path", "value": shutil.which("Rscript") or ""},
        {"key": "rscript_version", "value": _command_text(["Rscript", "--version"]) if shutil.which("Rscript") else ""},
        {"key": "torch_cuda_available", "value": _torch_cuda_available()},
    ]


def smoke_test_rows() -> list[dict[str, str]]:
    """Run lightweight import/package smoke checks."""

    rows = []
    rows.append(_python_smoke_row("python_base", BASE_PACKAGES))
    rows.append(_python_smoke_row("python_latent", LATENT_PACKAGES))
    rows.append(_r_smoke_row())
    return rows


def render_environment_markdown(
    runtime: pd.DataFrame,
    packages: pd.DataFrame,
    smoke_tests: pd.DataFrame,
) -> str:
    """Render a compact human-readable environment report."""

    lines = [
        "# Environment Report",
        "",
        "Generated by `make environment-report`.",
        "",
        "## Runtime",
        "",
        "| Key | Value |",
        "| --- | --- |",
    ]
    for _, row in runtime.iterrows():
        lines.append(f"| {row['key']} | `{row['value']}` |")

    lines.extend(["", "## Package Groups", "", "| Group | Present | Missing |", "| --- | ---: | ---: |"])
    group_counts = packages.groupby(["group", "status"], dropna=False).size().unstack(fill_value=0)
    for group, row in group_counts.iterrows():
        lines.append(f"| {group} | {int(row.get('present', 0))} | {int(row.get('missing', 0))} |")

    lines.extend(["", "## Smoke Tests", "", "| Test | Status | Detail |", "| --- | --- | --- |"])
    for _, row in smoke_tests.iterrows():
        lines.append(f"| {row['test']} | {row['status']} | {row['detail']} |")
    lines.append("")
    return "\n".join(lines)


def r_environment_yml() -> str:
    """Return the conda environment spec for R/Bioconductor analyses."""

    packages = "\n".join(
        [
            "  - r-base=4.4",
            "  - r-data.table",
            "  - r-optparse",
            "  - r-matrix",
            "  - bioconductor-edger",
            "  - bioconductor-limma",
            "  - bioconductor-singlecellexperiment",
            "  - bioconductor-milor",
        ]
    )
    return (
        "name: ora-r-bioconductor\n"
        "channels:\n"
        "  - conda-forge\n"
        "  - bioconda\n"
        "dependencies:\n"
        f"{packages}\n"
    )


def pip_freeze() -> str:
    """Return the current pip freeze output."""

    result = subprocess.run(
        [sys.executable, "-m", "pip", "freeze", "--all"],
        check=False,
        capture_output=True,
        text=True,
    )
    return result.stdout


def _python_smoke_row(test: str, specs: tuple[PackageSpec, ...]) -> dict[str, str]:
    missing = []
    for spec in specs:
        module_name = spec.module or spec.package.replace("-", "_")
        try:
            __import__(module_name)
        except Exception as exc:  # pragma: no cover - exercised by environment state
            missing.append(f"{module_name}: {exc.__class__.__name__}")
    return {
        "test": test,
        "status": "pass" if not missing else "fail",
        "detail": "all imports succeeded" if not missing else "; ".join(missing),
    }


def _r_smoke_row() -> dict[str, str]:
    rscript = shutil.which("Rscript")
    if not rscript:
        return {"test": "r_bioconductor", "status": "blocked", "detail": "Rscript not installed locally"}
    expression = "; ".join(f"suppressPackageStartupMessages(library({package}))" for package in R_PACKAGES)
    result = subprocess.run(
        [rscript, "-e", f"{expression}; cat('ok\\n')"],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        return {"test": "r_bioconductor", "status": "pass", "detail": "all R packages loaded"}
    detail = (result.stderr or result.stdout).strip().replace("\n", " ")
    return {"test": "r_bioconductor", "status": "fail", "detail": detail[:300]}


def _torch_cuda_available() -> str:
    try:
        import torch

        return str(bool(torch.cuda.is_available()))
    except Exception:
        return ""


def _command_text(command: list[str]) -> str:
    try:
        result = subprocess.run(command, check=False, capture_output=True, text=True)
    except FileNotFoundError:
        return ""
    text = (result.stdout or result.stderr).strip()
    return text.replace("\n", " ")
