#!/usr/bin/env python3
"""Check manuscript package assets before submission."""

from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

import pandas as pd


EXPECTED_EXTENDED_FIGURES = [
    "extended_data_figure1_model_card.pdf",
    "extended_data_figure2_external_evidence.pdf",
    "extended_data_figure3_scvi_validation.pdf",
    "extended_data_figure4_de_audit.pdf",
    "extended_data_figure5_latent_robustness.pdf",
    "extended_data_figure6_ndd_guardrails.pdf",
]

EXPECTED_MANUSCRIPT_TABLES = [
    "manuscript_table_cohort.tsv",
    "manuscript_table_model_card.tsv",
    "manuscript_table_external_validation_strength.tsv",
    "manuscript_table_latent_neighborhood_gates.tsv",
    "manuscript_table_de_audit_summary.tsv",
    "manuscript_table_ndd_guardrails.tsv",
]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manuscript", default="manuscript/main.tex")
    parser.add_argument("--bib", default="manuscript/references.bib")
    parser.add_argument("--figures-dir", default="results/figures")
    parser.add_argument("--tables-dir", default="results/tables")
    parser.add_argument("--out", default="results/reports/manuscript_package_check.tsv")
    parser.add_argument("--markdown-out", default="docs/manuscript_package_check.md")
    args = parser.parse_args()

    rows = check_package(
        manuscript=Path(args.manuscript),
        bib=Path(args.bib),
        figures_dir=Path(args.figures_dir),
        tables_dir=Path(args.tables_dir),
    )
    table = pd.DataFrame(rows, columns=["check", "status", "detail"])
    _write_tsv(table, Path(args.out))
    _write_text(render_markdown(table), Path(args.markdown_out))
    failures = table["status"].eq("fail").sum()
    blocked = table["status"].eq("blocked").sum()
    print(f"Wrote manuscript package check: {args.out} ({len(table)} checks; {failures} fail; {blocked} blocked)")
    print(f"Wrote manuscript package audit: {args.markdown_out}")
    if failures:
        raise SystemExit(1)


def check_package(
    *,
    manuscript: Path,
    bib: Path,
    figures_dir: Path,
    tables_dir: Path,
) -> list[dict[str, str]]:
    tex = manuscript.read_text(encoding="utf-8") if manuscript.exists() else ""
    bib_text = bib.read_text(encoding="utf-8") if bib.exists() else ""
    rows: list[dict[str, str]] = []

    rows.append(_existence_row("manuscript_source", manuscript))
    rows.append(_existence_row("bibliography_source", bib))
    rows.append(_citation_row(tex, bib_text))
    rows.extend(_main_figure_rows(tex, figures_dir))
    rows.extend(_expected_file_rows("extended_data_figure", figures_dir, EXPECTED_EXTENDED_FIGURES))
    rows.extend(_table_rows(tables_dir))
    rows.append(_tex_engine_row())
    return rows


def render_markdown(table: pd.DataFrame) -> str:
    lines = [
        "# Manuscript Package Check",
        "",
        "Updated: 2026-06-23",
        "",
        "This audit is generated by `make manuscript-check`. A `blocked` TeX row means the local machine lacks a TeX engine; it is not a manuscript asset failure.",
        "",
        "| Check | Status | Detail |",
        "| --- | --- | --- |",
    ]
    for _, row in table.iterrows():
        lines.append(f"| `{row['check']}` | {row['status']} | {row['detail']} |")
    lines.append("")
    return "\n".join(lines)


def _citation_row(tex: str, bib_text: str) -> dict[str, str]:
    cite_keys = _citation_keys(tex)
    bib_keys = set(re.findall(r"@\w+\s*\{\s*([^,]+)", bib_text))
    missing = sorted(cite_keys - bib_keys)
    unused = sorted(bib_keys - cite_keys)
    if missing:
        return {
            "check": "citation_keys",
            "status": "fail",
            "detail": "missing from bibliography: " + ", ".join(missing),
        }
    return {
        "check": "citation_keys",
        "status": "pass",
        "detail": f"{len(cite_keys)} cited keys resolve; {len(unused)} unused bibliography keys.",
    }


def _citation_keys(tex: str) -> set[str]:
    keys: set[str] = set()
    pattern = re.compile(r"\\cite\w*\*?(?:\[[^\]]*\]){0,2}\{([^}]+)\}")
    for match in pattern.finditer(tex):
        keys.update(key.strip() for key in match.group(1).split(",") if key.strip())
    return keys


def _main_figure_rows(tex: str, figures_dir: Path) -> list[dict[str, str]]:
    refs = re.findall(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", tex)
    rows = []
    for ref in refs:
        rows.append(_existence_row(f"main_figure:{ref}", figures_dir / ref))
    if not refs:
        rows.append({"check": "main_figures", "status": "fail", "detail": "No includegraphics references found."})
    return rows


def _expected_file_rows(prefix: str, base_dir: Path, filenames: list[str]) -> list[dict[str, str]]:
    return [_existence_row(f"{prefix}:{name}", base_dir / name) for name in filenames]


def _table_rows(tables_dir: Path) -> list[dict[str, str]]:
    rows = []
    for name in EXPECTED_MANUSCRIPT_TABLES:
        path = tables_dir / name
        row = _existence_row(f"manuscript_table:{name}", path)
        if path.exists():
            n_lines = sum(1 for _ in path.open(encoding="utf-8"))
            row["detail"] += f"; {max(n_lines - 1, 0)} data rows"
        rows.append(row)
    return rows


def _tex_engine_row() -> dict[str, str]:
    latexmk = shutil.which("latexmk")
    pdflatex = shutil.which("pdflatex")
    bibtex = shutil.which("bibtex")
    if latexmk:
        return {"check": "tex_engine", "status": "pass", "detail": f"latexmk available at {latexmk}"}
    if pdflatex and bibtex:
        return {"check": "tex_engine", "status": "pass", "detail": "pdflatex and bibtex available"}
    return {
        "check": "tex_engine",
        "status": "blocked",
        "detail": "No local latexmk or pdflatex+bibtex; run `make manuscript` in a TeX-enabled environment.",
    }


def _existence_row(check: str, path: Path) -> dict[str, str]:
    if not path.exists():
        return {"check": check, "status": "fail", "detail": f"missing: {path}"}
    size = path.stat().st_size
    if size <= 0:
        return {"check": check, "status": "fail", "detail": f"empty file: {path}"}
    return {"check": check, "status": "pass", "detail": f"{path} ({size} bytes)"}


def _write_tsv(table: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    table.to_csv(path, sep="\t", index=False)


def _write_text(text: str, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
